name: Create-Docker

on:
  workflow_run:
    workflows: [Build-Nightly]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    name: Creat Docker Nightly Image

    runs-on: ubuntu-latest
# docker push docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:nightly
    steps:
    - name: Step 1 - Setup Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3.3.1

    - uses: actions/checkout@v2
      name: Step 2 - Checkout Git Repo
    - name: Step 3 - Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io
        docker buildx build . --file Dockerfile --push --platform inux/amd64,linux/arm64,linux/arm --tag docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:nightly
        
