# This is a basic workflow to help you get started with Actions

name: Create-Doc

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doc:
    name: Create Doc
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: Step 1 - Checkout Nightly Branch
  
      # Runs a single command using the runners shell
      - name: Step 2 - Setup JDK 17
        uses: actions/setup-java@v3.4.1
        with: 
          java-version: 17
          distribution: 'temurin'

      - name: Step 7 - Create Doc
        run: mvn dokka:dokka -f pom.xml
      - name: Step 8 - Move Doc folder
        run: mv -r target/dokka/* docs
      - name: Step 9 - Push new Doc
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: nightly
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
