# This is a basic workflow to help you get started with Actions

name: Nightly-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "nightly" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: Step 1 - Checkout Nightly Branch

      # Runs a single command using the runners shell
      - name: Step 2 - Setup JDK 17
        uses: actions/setup-java@v3.4.1
        with: 
          java-version: 17
          distribution: 'temurin'

      # Runs a set of commands using the runners shell
      - name: Step 3 - Build Maven Project
        run: mvn -B package --file pom.xml
        
      - name: Step 4 - List Current Directory
        run: ls -a
        
      - name: Step 5 - List Target Folder
        run: |
          cd target
          ls -a
          
      - name: Step 6 - Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
            artifacts: "target/*.jar"
            prerelease: true
            tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
